# Shell variables
# Generated by 'wal'
wallpaper="/home/sacha/Pictures/Wallpapers/Tower-Night.png"

# Special
background='#13122b'
foreground='#c4c3ca'
cursor='#c4c3ca'

# Colors
color0='#13122b'
color1='#0662B0'
color2='#4349A5'
color3='#0377C6'
color4='#9A6DB2'
color5='#059DE3'
color6='#42A4E1'
color7='#c4c3ca'
color8='#626177'
color9='#0662B0'
color10='#4349A5'
color11='#0377C6'
color12='#9A6DB2'
color13='#059DE3'
color14='#42A4E1'
color15='#c4c3ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
