--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sacha/Pictures/Wallpapers/Sunset-Forrest.png"

-- Special
background="#0b0b1e"
foreground="#cab3b8"
cursor="#cab3b8"

-- Colors
color0="#0b0b1e"
color1="#674860"
color2="#8D3C4D"
color3="#9C5B64"
color4="#D6736C"
color5="#EF9970"
color6="#FBCF78"
color7="#cab3b8"
color8="#8d7d80"
color9="#674860"
color10="#8D3C4D"
color11="#9C5B64"
color12="#D6736C"
color13="#EF9970"
color14="#FBCF78"
color15="#cab3b8"
