--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sacha/Pictures/Wallpapers/Tower-Night.png"

-- Special
background="#13122b"
foreground="#c4c3ca"
cursor="#c4c3ca"

-- Colors
color0="#13122b"
color1="#0662B0"
color2="#4349A5"
color3="#0377C6"
color4="#9A6DB2"
color5="#059DE3"
color6="#42A4E1"
color7="#c4c3ca"
color8="#626177"
color9="#0662B0"
color10="#4349A5"
color11="#0377C6"
color12="#9A6DB2"
color13="#059DE3"
color14="#42A4E1"
color15="#c4c3ca"
